name: Generate PacMan Animation
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate PacMan
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/pacman.svg
          # ðŸ‘‡ Tell SNK to use the PacMan simulation:
          mode: pacman

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pacman
          path: dist/pacman.svg
